controllers:
    resource: ../src/Controller/
    type: annotation
    defaults:
        schemes: [https]

api_controllers:
    resource: ../src/Controller/API/
    type: annotation
    prefix: /api
    condition: 'context.getHost() == env("BASE_HOST")'
    defaults:
        schemes: [https]

kernel:
    resource: ../src/Kernel.php
    type: annotation
