#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if which composer >/dev/null; then
  composer install --ansi --no-interaction --no-progress --prefer-dist --optimize-autoloader
fi

if which npm >/dev/null; then
  npm install
fi
