#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if which composer >/dev/null; then
  composer validate
fi

if which php >/dev/null; then
  php bin/phpunit
fi

if which npx >/dev/null; then
  npx lint-staged --relative
fi
