# https://docs.github.com/en/actions

name: Deploy manually

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      HOST:
        required: true
        type: choice
        description: ""
        options:
          - production
          - staging
      TAG:
        description: ""
        required: false
        type: string
      BRANCH:
        description: ""
        required: false
        type: string
    secrets:
      PRIVATE_KEY:
        required: true

# It is important to specify "concurrency" for the workflow,
# to prevent concurrency between different deploys.
concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.HOST && (github.event.inputs.TAG || github.event.inputs.BRANCH) }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/deploy.yml
        with:
          HOST: ${{ github.event.inputs.HOST }}
          TAG: ${{ github.event.inputs.TAG }}
          BRANCH: ${{ github.event.inputs.BRANCH }}
          PRIVATE_KEY: ${{ github.event.secrets.PRIVATE_KEY }}
