# https://docs.github.com/en/actions

name: Deploy

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      HOST:
        required: true
        type: string
      TAG:
        required: false
        type: string
      BRANCH:
        required: false
        default: "main"
        type: string
    secrets:
      PRIVATE_KEY:
        required: true
      SENTRY_AUTH_TOKEN:
        required: false
      SENTRY_ORG:
        required: false
      SENTRY_PROJECT:
        required: false
      NEW_RELIC_API_KEY:
        required: false


# It is important to specify "concurrency" for the workflow,
# to prevent concurrency between different deploys.
concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ inputs.HOST && (inputs.TAG || inputs.BRANCH) }}
    steps:
      - uses: actions/checkout@v3
#      - uses: ./.github/actions/setup-environment
#
#      - name: Deploy tag ${{ inputs.TAG }} to ${{ inputs.HOST }}
#        if: ${{ inputs.TAG }}
#        uses: deployphp/action@v1
#        with:
#          private-key: ${{ secrets.PRIVATE_KEY }}
#          dep: deploy --tag=${{ inputs.TAG }} -n -vvv ${{ inputs.HOST }}
#
#      - name: Deploy branch ${{ inputs.BRANCH }} to ${{ inputs.HOST }}
#        if: ${{ inputs.BRANCH }}
#        uses: deployphp/action@v1
#        with:
#          private-key: ${{ secrets.PRIVATE_KEY }}
#          dep: deploy --branch=${{ inputs.BRANCH }} -n -vvv ${{ inputs.HOST }}

      - uses: ./.github/workflows/sentry.yml
        with:
          HOST: ${{ inputs.HOST }}
          TAG: ${{ inputs.TAG }}
          BRANCH: ${{ inputs.BRANCH }}

      - uses: ./.github/workflows/new_relic.yml
        with:
          HOST: ${{ inputs.HOST }}
          TAG: ${{ inputs.TAG }}
          BRANCH: ${{ inputs.BRANCH }}
