# https://docs.github.com/en/actions

name: "Integrate"

on: # yamllint disable-line rule:truthy
  pull_request: null
  workflow_call: null
  push:
    branches:
      - "main"

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  cypress:
    runs-on: ubuntu-latest
    name: cypress
    steps:
      - uses: actions/checkout@v3
