# https://docs.github.com/en/actions

name: New Relic monitoring

on: # yamllint disable-line rule:truthy
  workflow_call:
    secrets:
      NEW_RELIC_API_KEY:
        required: true


jobs:
  monitoring:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v3
      - uses: arnaud-ritti/nr-monit@main
        with:
          config: ".github/monitors.yml"
          api_key: ${{ secrets.NEW_RELIC_API_KEY }}
          eu_server: true
