# https://docs.github.com/en/actions

name: Deploy

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      HOST:
        required: true
        type: string
      TAG:
        required: false
        type: string
      BRANCH:
        required: false
        default: "main"
        type: string
    secrets:
      SENTRY_AUTH_TOKEN:
        required: true
      SENTRY_ORG:
        required: true
      SENTRY_PROJECT:
        required: true


jobs:
  sentry:
    runs-on: ubuntu-latest
    if: ${{ inputs.HOST && (inputs.TAG || inputs.BRANCH) }}
    steps:
      - name: Create Sentry release for ${{ inputs.BRANCH }}
        if: ${{ inputs.BRANCH }}
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: ${{ inputs.HOST }}

      - name: Create Sentry release for ${{ inputs.TAG }}
        if: ${{ inputs.TAG }}
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: ${{ inputs.HOST }}
          version: ${{ inputs.TAG }}
